### ISSUE TITLE
help find your package

### ISSUE THREAD

**Issue by Scrum** [posthtml/posthtml-highlight#17]
@caseyWebb Hi, I am a posthtml package maintainer, I found your package because you have a posthtml package in dependencies. I think it will be easier for people to find your package if you add it to the list of plugins [here](https://github.com/posthtml/posthtml#plugins) and [here](https://github.com/posthtml/posthtml-plugins/), and of course the first thing to do in the posthtml organization itself - I can move your package to the posthtml organization for more popularity, for this it will be necessary to add me to this repository and then I will transfer it. The package itself will remain under your control.

let me know about any decision you make, i will understand if you are not interested

**Comment by caseyWebb** [comment]
I've added you as a collaborator and will submit PRs to the plugin lists above shortly

**Comment by Scrum** [comment]
@caseyWebb Unfortunately, these rights are not enough to translate into an organization, I must be owner to have an option `settings` where can i do the transfer to posthtml org

**Comment by caseyWebb** [comment]
I was wondering about that. I've initiated the transfer.

**Comment by caseyWebb** [comment]
:tada:
