### ISSUE TITLE
Deprecation notice when using class .language-*

### ISSUE THREAD

**Issue by azan-n** [posthtml/posthtml-highlight#559]
Node - `16.13.0`
HighlightJS - `11.3.1`
PostHTML - `0.16.5`
posthtml-highlight - `1.1.2`

I really appreciate you creating this plugin and have been using it with Parcel v2 using a simple `.posthtmlrc` which is as follows:
```
{
    "plugins": {
        "posthtml-highlight": {
            "inline": true
        }
    }
}
```

This allows me ship highlighted code-blocks in my website without shipping hljs with it however in areas where the highlighting isn't working properly, I add the language specific classes like `.language-cpp` to the `<code>` element which invariably leads to this notice on build-time which I do not get when they are removed.

```
console: Deprecated as of 10.7.0. highlight(lang, code, ...args) has been deprecated.
console: Deprecated as of 10.7.0. Please use highlight(code, options) instead.
https://github.com/highlightjs/highlight.js/issues/2277
```

Even though the `src/index.ts` of this project suggests that this notice shouldn't be shown, I could be wrong in my superficial reading of the code. I'm just bringing this to your notice to test out.

Cheers

**Comment by caseyWebb** [comment]
oops, latest version didn't get published to npm.

You should now be able to upgrade to posthtml-highlight 3.0.0 and resolve this warning. Breaking changes between 1.1.2 and 3.0.0 are in CHANGELOG.md, but for convenience:

- dropped support for Node <10
- highlightjs language aliases changed upstream (https://github.com/highlightjs/highlight.js/blob/main/VERSION_11_UPGRADE.md)
